- src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb
- src/bosh_aws_cpi/spec/unit/instance_manager_spec.rb
Instance creation was incorrectly logging a warning of "IP address was in
use" when the API request had failed due to rate limiting. This is because
2953c67 extended the existing `Bosh::Common.retryable` block without
changing the condition that warnings were logged on.
Fix this by only logging a warning if the exception indicates that the IP
address is invalid. We no longer need to check the number of tries, because
`error` is always `nil` on the first loop.
The tests feel slightly brittle and laboured in that they are matching the
existence and non-existence of some text. But it does seem like it's worth
testing for.
> Omit "IP address" warning on rate limit exception

- jobs/aws_cpi/spec
- jobs/aws_cpi/templates/cpi.json.erb
- src/bosh_aws_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
This covers part of the issue described in #19 
This PR adds the property `aws.max_retries` to the spec and the `cpi.json`
template. This option is passed to the AWS Ruby SDK library:
http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/Core/Configuration.html#max_retries-instance_method
and it allows specify the maximum number of times AWS service errors (500) and
throttling errors should be retried. There is an exponential backoff in
between retries, so the more retries the longer it can take to fail.
Increasing this number would mitigate the errors caused Request Rate Limit from AWS. 
The option `aws.max_retries` [is already implemented in the CPI ruby code](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/118ea6df1fd6c9f9c2116a5e47a27cfb33e834c9/src/bosh_aws_cpi/lib/clou …
> Add support for the property aws.max_retries for AWS Ruby SDK

- src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb
- src/bosh_aws_cpi/spec/unit/instance_manager_spec.rb
Allows define security groups in the resource pool definition of an
instance.
The list of security groups will have precendence over the network specification
security group and default aws security group. I think that makes sense
as the user can rely on spiff/spruce to include the security groups from
a shared definition is required. Anyway, this point can be discussed
This fixes https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/issues/27
Note: If accepted, it requires update the documentation in https://github.com/cloudfoundry/docs-bosh/blob/master/aws-cpi.html.md.erb#L62
> Allow define security groups in resource_pool

- jobs/aws_cpi/templates/cpi.json.erb
- src/bosh_aws_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
The registry password might include non valid characters and must be
encoded when rendering the registry endpoint.
This fixes https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/issues/18
> Encode registry password when rendering URI

- src/bosh_aws_cpi/lib/cloud/aws/cloud.rb
- src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb
- src/bosh_aws_cpi/lib/cloud/aws/resource_wait.rb
- src/bosh_aws_cpi/spec/unit/attach_disk_spec.rb
- src/bosh_aws_cpi/spec/unit/instance_manager_spec.rb
As per #23 and #19 the logic to retry when there is a RequestLimitExceded is in the client library code, so it is not needed at an upper level. 
This PR removes the logic added in several places to retry requests when the `RequestLimitExceded` exception is raised. Often this logic is related to other potential errors, so only the condition on this specific error has been removed.
I got special doubts about the file `resource_wait.rb`, which implements wrappers for several resources. `RequestLimitExceded` was the default error to retry, and after removing it, it left some of this resources with some retry logic which will not be ever activated. 
* if this PR is merged, it must be done after #23. 
* It also includes de code from #23, so it might need rebasing. 
* be aware that this will …
> Remove AWS RequestLimitExceded retries at the BOSH CPI Level

- src/bosh_aws_cpi/lib/cloud/aws/instance.rb
- src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb
- src/bosh_aws_cpi/spec/unit/instance_spec.rb
The `advertised_instance_routes` cloud property on resource pools/vm
types has been added to allow manifests to connect routes on AWS
Routing Tables with specific instances, if you need to route traffic
through a BOSH deployed VM (like in the case of a site-to-site VPN).
If using this, it is recommended to only have a single instance of a
single job of that resource pool, to avoid confusion. If there are
multiple instances/jobs in the resource pool, the last one processed
will be the node assigned to the route.
Datastructure of `advertised_instance_routes` is as follows:
```
cloud_properties:
advertised_instance_routes:
- table_id:    rt-abcdef123
destination: 10.0.0.0/16
- table_id:    rt 12345abcd
destination: 10.0.0.0/16
```
This allows the manifest to specify that multiple routing …
> Add support for updating AWS routing table entries

- src/bosh_aws_cpi/lib/cloud/aws/instance.rb
- src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb
- src/bosh_aws_cpi/spec/spec_helper.rb
- src/bosh_aws_cpi/spec/unit/instance_manager_spec.rb
- src/bosh_aws_cpi/spec/unit/instance_spec.rb
The ability to set the 'source/destination check' network property is useful for instances performing cross-VPC routing. This allows a resource pool property to set this, it defaults to 'true' which is the AWS default.
```
- name: my-vpn-server
cloud_properties:
source_dest_check: false
```
> add the ability to set the network property 'source/destination check'

- ci/assets/terraform/template.tf
- ci/tasks/run-integration.sh
- src/bosh_aws_cpi/spec/integration/lifecycle_spec.rb
- Terraform generates IPv6 CIDR, address, propagates to
integration test
- minor reformatting of Terraform template
- adjust instance type to t2.small; m3.medium does NOT work:
`"IPv6 is not supported for the instance type 'm3.medium'"`
> Test IPv6 static IP assignment

- ci/assets/terraform/template.tf
- ci/tasks/run-integration.sh
- docs/development.md
- jobs/aws_cpi/spec
- jobs/aws_cpi/templates/cpi.json.erb
- src/bosh_aws_cpi/bin/test-integration
- src/bosh_aws_cpi/lib/cloud/aws/config.rb
- src/bosh_aws_cpi/spec/integration/aws_cpi_spec.rb
- src/bosh_aws_cpi/spec/integration/endpoint_spec.rb
- src/bosh_aws_cpi/spec/integration/lifecycle_spec.rb
- src/bosh_aws_cpi/spec/integration/light_stemcell_spec.rb
- src/bosh_aws_cpi/spec/integration/manual_network_spec.rb
- src/bosh_aws_cpi/spec/integration/resources/classic_lb_spec.rb
- src/bosh_aws_cpi/spec/integration/resources/lb_target_group_spec.rb
- src/bosh_aws_cpi/spec/integration/spec_helper.rb
- src/bosh_aws_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
Allow optionally define the `session_token` attribute together with the `access_key_id` and the `secret_access_key`, enabling the user of the CPI to use all the possible authentication mechanism in AWS.
This PR extends the feature and allows run the integration tests using STS credentials.
This covers the use cases from the issue #60
Use cases and justification
--------------------------
As developers and operators, we should avoid use permanent AWS credentials that might be leaked and then abused. We should encourage and allow to use [AWS Temporary Security credentials (STS)](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html).
These credentials have a maximum TTL of 36 hours.
It has been argued that is pointless to use these kind of credentials with the CPI, but …
> Implement support for static STS credentials

- src/bosh_aws_cpi/lib/cloud/aws/aws_provider.rb
- src/bosh_aws_cpi/spec/unit/aws_provider_spec.rb
This addresses issue - https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/issues/65 for setup where elb endpoint is signed by custom ssl cert
> added cert file for bosh ca certs to initialization of elb client

- src/bosh_aws_cpi/lib/cloud/aws/cloud.rb
- src/bosh_aws_cpi/spec/integration/manual_network_spec.rb
- src/bosh_aws_cpi/spec/unit/snapshot_disk_spec.rb
- custom tags are already added when creating volumes and
VMs, so this just makes snapshots consistent.
[#150754225](https://www.pivotaltracker.com/story/show/150754225)
Signed-off-by: Beyhan Veli <beyhan.veli@sap.com>
> Add custom tags to snapshot volumes

- src/bosh_aws_cpi/lib/cloud/aws/cloud_props.rb
- src/bosh_aws_cpi/lib/cloud/aws/instance_param_mapper.rb
- src/bosh_aws_cpi/spec/unit/instance_param_mapper_spec.rb
- allows users to override auto assign public ips when subnets have this
enabled by default
Fixes https://github.com/cloudfoundry/bosh/issues/1885
[finishes #154861697](https://www.pivotaltracker.com/story/show/154861697)
> Allow users to override auto_assign_public_ip to false

- src/bosh_aws_cpi/lib/cloud/aws/aws_provider.rb
- src/bosh_aws_cpi/lib/cloud/aws/cloud_core.rb
- src/bosh_aws_cpi/lib/cloud/aws/cloud_v1.rb
[#166975601](https://www.pivotaltracker.com/story/show/166975601)
The AWS CPI makes requests unnecessarily often to the AWS API which leads to `RequestLimitExceeded`.
In particular, the `describe_subnets` API is called too often.
We have observed deployments with several hundreds of instances where `describe_subnets` gets called thousands of times.
Thanks @istvanballok for figuring this out.
This PR serves as discussion how to minimize the number of AWS API calls.
Deploy a single instance, e.g. the following deployment using the latest AWS CPI release (v75)
```
---
name: zookeeper
releases:
- name: zookeeper
version: 0.0.10
stemcells:
- alias: default
os: ubuntu-xenial
version: latest
update:
...
instance_groups:
- name: zookeeper
azs: [z1]
instances: 1
jobs:
- name: zookeeper
release: …
```
> Remove unnecessary describe_subnets calls

- src/bosh_aws_cpi/lib/cloud/aws/spot_manager.rb
- src/bosh_aws_cpi/spec/unit/spot_manager_spec.rb
What
----
The CPI creates instances using two separate AWS API calls:
1. `#run_instances`
2. `#request_spot_instances`
The `#run_instances` method takes `:tag_specifications` as an argument whereas the `#request_spot_instances` method does not
If we receive `:tag_specifications` in our `launch_specification` we should (for spot instances)
1. not pass it on to the `#request_spot_instances` method
2. create the desired tags after our instance is created
Source: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#request_spot_instances-instance_method
> CPI tags work for spot instances

- src/bosh_aws_cpi/bin/stemcell-copy
- src/bosh_aws_cpi/lib/cloud/aws/stemcell_creator.rb
Instead of running the entire `stemcell-copy` as root, which is unnecessary, we restrict root privileges to the single `dd` command.
This lays the groundwork for allowing non-privileged users to run `bosh create-env` without root privileges (by moving `sudo` out of the CPI and into a helper script which can be swapped in for a different, sudo-less, helper script).
> `sudo` the one executable, not the entire script

- src/bosh_aws_cpi/lib/cloud/aws.rb
- src/bosh_aws_cpi/lib/cloud/aws/cloud_core.rb
- src/bosh_aws_cpi/lib/cloud/aws/cloud_v1.rb
- src/bosh_aws_cpi/lib/cloud/aws/resource_wait.rb
- src/bosh_aws_cpi/lib/cloud/aws/sdk_helpers/volume_manager.rb
- src/bosh_aws_cpi/lib/cloud/aws/sdk_helpers/volume_modification.rb
- src/bosh_aws_cpi/spec/integration/manual_network_spec.rb
- src/bosh_aws_cpi/spec/unit/resize_disk_spec.rb
* this change allows to resize volumes using the AWS API
* the change is analogous to the change inside the BOSH Openstack CPI: https://github.com/cloudfoundry/bosh-openstack-cpi-release/commit/d081938852ecae502c0ba285020996a4a0c0d01d
* to use this feature the bosh director configuration enable_cpi_resize_disk needs to be enabled
> Add a new API method resize_disk

- src/bosh_aws_cpi/lib/cloud/aws/resource_wait.rb
Resizing a disk e.g. from 2TB to 4TB can easily
take an hour or more, so we increase the timeout
for this operation to around 100 minutes
(4 times the default timeout of around 25 minutes)
Fixes issue #116
> Increase timeout for volume modification

- jobs/aws_cpi/spec
- jobs/aws_cpi/templates/cpi.json.erb
- src/bosh_aws_cpi/lib/cloud/aws/cloud_v1.rb
- src/bosh_aws_cpi/lib/cloud/aws/config.rb
- src/bosh_aws_cpi/lib/cloud/aws/resource_wait.rb
- src/bosh_aws_cpi/lib/cloud/aws/sdk_helpers/volume_manager.rb
- src/bosh_aws_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
- src/bosh_aws_cpi/spec/unit/resize_disk_spec.rb
- src/bosh_aws_cpi/spec/unit/resource_wait_spec.rb
- src/bosh_aws_cpi/spec/unit/volume_manager_spec.rb
As announced in #116 few days ago, here is a patch implementing a configurable timeout scale factor for IaaS-native disk resize operations.
As discussed, increasing the timeout is useful for successfully resizing very large disks.
This patch here overrides the hardcoded factor of `4` that has already been merged with #117, and the value of `4` is kept as the default.
> Configurable timeout factor for IaaS-native disk resize

- src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb
Adding missing m6i and r6i to nvem families.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances
> Adding missing m6i and r6i types to nvme families

- jobs/aws_cpi/spec
- jobs/aws_cpi/templates/cpi.json.erb
- src/bosh_aws_cpi/lib/cloud/aws/cloud_v1.rb
- src/bosh_aws_cpi/lib/cloud/aws/config.rb
- src/bosh_aws_cpi/lib/cloud/aws/resource_wait.rb
- src/bosh_aws_cpi/lib/cloud/aws/sdk_helpers/volume_manager.rb
- src/bosh_aws_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
- src/bosh_aws_cpi/spec/unit/resize_disk_spec.rb
- src/bosh_aws_cpi/spec/unit/resource_wait_spec.rb
- src/bosh_aws_cpi/spec/unit/volume_manager_spec.rb
Hi there,
In #122, we've seen that when resizing disks, the `optimizing` state is only a backend concern on the AWS EBS servers infrastructure, for delivering the promised performance. So for a Bosh CPI concern, there is no need to wait for the EBS backend reorganisation to finish with the `completed` state. This is good news as our production clusters were taking days for the optimisations to finish.
Here in this PR, we provide an implementation for the CPI to move on once the [VolumeModification](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VolumeModification.html) reaches the `optimizing` or `completed` states.
With this new approach, the `aws.extend_ebs_volume.wait_time_factor` config property introduced in #119 is no more necessary, so it has been removed. Which is also …
> Fast AWS-native disk resize

- src/bosh_aws_cpi/Gemfile
- src/bosh_aws_cpi/Gemfile.lock
During my tests for the GP3 throughput and iops PR #126 I had the issue that the CPI would emit errors on compile: 
`set_default_engine': Unable to find a compatible xml library. Ensure that you have installed or added to your Gemfile one of ox, oga, libxml, nokogiri or rexml (RuntimeError)
I checked the Gemfile and Gemfile.lock and saw rexml was not being vendored, as the only Gem requiring it was crack, which in turn was required by webmock. This caused no xml runtime to be present.
Why this worked in the past or currently on release building, I do not know, but adding the Gem to the Gemfile made it so dev releases were able to compile and run on a BOSH director.
> Add rexml as top level dependency

- docs/development.md
- src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb
- src/bosh_aws_cpi/lib/cloud/aws/cloud_props.rb
- src/bosh_aws_cpi/lib/cloud/aws/cloud_v1.rb
- src/bosh_aws_cpi/lib/cloud/aws/volume_properties.rb
- src/bosh_aws_cpi/spec/unit/block_device_manager_spec.rb
Adding support for both iops and throughput values of GP3 disks. 
- Added tests that test iops and throughput in the same fashion as io1s iops are tested
- Works on root, ephemeral and persistent disks.
- Note: values below the base of 3000 iops and 125mbps that are specified will be bumped by amazon to the baseline. 
- Test suite for block_device_manager are green. Due to me not having a playground AWS account I have not ran the full suite (as I did not touch most of the CPI)
- Manual integration test on AWS done.
> Gp3 throughput and IOPS support

- docs/development.md
Update development.md with working instructions for running the unit tests.
NOTE: The previous instructions resulted in script errors, since the script can't be executed from the project's root dir using the previously-documented commands.
> Fix development.md unit testing instructions

- src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb
adding the c6i instances to the nvme families following convention seen in https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/121/commits
> adding c6i to nvme families

- src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb
I've had trouble locally getting this running on a test aws account but i think i might have covered what's required.  Wanting to add i3en types.  I can add separate tests if needed but the way they were written its more against the raw_storage_instance then the type itself.
> adding i3en types

- src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb
Adding the remainder of general generations from https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances
I've specifically left of the i4i types as they are special case for storage types.
These are all listed with NVMe EBS
All tests passed from ./bin/test-unit
> Adding missing nvme/nitro types

- src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb
Adding the i4i, im4gn, is4gen machine types to the block device manager for the use of things like the below.
```
- cloud_properties:
instance_type: i4i.large
use_instance_storage: true
name: ds.i4i.large
- cloud_properties:
ephemeral_disk:
size: 25000
type: gp3
instance_type: i4i.large
name: i4i.large
```
- Tested manually through bosh director of using zookeeper with both instance types above
- Unit tests all passed locally.
- Tested with basic test with zookeeper.
- ./bin/test-unit ran and passed.
- To use the use_instance_storage properly you have to add the map per instance type and pulled them from here - https://aws.amazon.com/ec2/instance-types/i4i/ and here https://aws.amazon.com/ec2/instance-types/i4g/.
Example below.
```
instance_groups:
- name: zookeeper
azs: [z1, z2, z3] …
```
> adding i4i and storage maps

- ci/assets/terraform/template.tf
- ci/pipeline.yml
- ci/tasks/run-integration.sh
- ci/tasks/run-integration.yml
- jobs/aws_cpi/spec
- jobs/aws_cpi/templates/cpi.json.erb
- src/bosh_aws_cpi/bin/test-integration
- src/bosh_aws_cpi/lib/cloud/aws/config.rb
- src/bosh_aws_cpi/spec/integration/lifecycle_spec.rb
- src/bosh_aws_cpi/spec/integration/manual_network_spec.rb
- src/bosh_aws_cpi/spec/integration/spec_helper.rb
- src/bosh_aws_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
- src/bosh_aws_cpi/spec/unit/config_spec.rb
The CPI will use assume role authentication if a role_arn is specified by the user in the cpi.json file.
Also, the integration tests, bats and e2e tests now use an assumed role to work.
The pipeline has changed to reflect this and now include the roles to be assumed.
[#184632801] Add AssumeRole support to bosh-aws-cpi
> Add assume role support in the AWS CPI

- src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb
Adds support for general purpose and RAM optimized 7th gen vm types.
https://aws.amazon.com/about-aws/whats-new/2023/08/amazon-ec2-m7i-flex-m7i-instances/
https://aws.amazon.com/about-aws/whats-new/2023/09/amazon-ec2-r7iz-instances/
> Add support for 7th gen vm types

- src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb
Add support for 7th gen compute optimized vm types
https://aws.amazon.com/ec2/instance-types/c7i/
> Add support for 7th gen compute optimized vm types

- jobs/aws_cpi/spec
From the current descrition it wasn't clear what format was expected here (string, array, hash, etc.). This example should make things clearer
> Add an example for aws metadata options

- packages/bosh_aws_cpi/packaging
We've seen some failures because it was simply using "bundle install" which does not properly install the gems into BOSH_INSTALL_TARGET.
After upgrading to ruby 3.2 it seems that the gems instead are installed into /usr/local/bundle which does not transfer from the compilation VM into the package so when the CPI is later invoked the gems are missing.
Copied the pattern from the [bosh director packaging script](https://github.com/cloudfoundry/bosh/blob/34d6a88dfae3cd505df72e73d99a2d94b04b0e0a/packages/director/packaging#L45)
> Fix gem bundle call during packaging

- src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb
Correcting some instance types that use NVMe (e.g. there is no P4 type, only p4d, there is g4ad and g4dn , also a new p5).  This is for use with the GenAI bosh release.
> New NVMe instance types

- src/bosh_aws_cpi/lib/cloud/aws/aws_provider.rb
- src/bosh_aws_cpi/spec/unit/aws_provider_spec.rb
AWS not support IPv6 with the normal endpoints. They introduced new endpoints: https://docs.aws.amazon.com/ec2/latest/devguide/ec2-endpoints.html
Luckily the AWS-RUBY-SDK already support this endpoint. It's only necessary to set the use_dualstack_endpoint parameter. As this support ipv4 and ipv6, i think we can use this as default.
> Use the dualstack support of the aws-sdk to support IPv6

- src/bosh_aws_cpi/lib/cloud/aws/aws_provider.rb
- src/bosh_aws_cpi/lib/cloud/aws/config.rb
- src/bosh_aws_cpi/spec/integration/aws_cpi_spec.rb
- src/bosh_aws_cpi/spec/spec_helper.rb
- src/bosh_aws_cpi/spec/unit/aws_provider_spec.rb
- src/bosh_aws_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
Based on https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/163, i added a config parameter to enable this feature.
> Add a config parameter to enable dualstack if needed

- jobs/aws_cpi/spec
- jobs/aws_cpi/templates/cpi.json.erb
Add templates that missing in https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/166
> Adapt templates correctly

- ci/pipeline.yml
- ci/tasks/build-candidate.sh
- ci/tasks/run-unit-specs.sh
- ci/tasks/run-unit-specs.yml
- ci/utils.sh
- run this before bumping dependencies
- run this as a separate task in the `build-candidate` job
- cleanup task definitions to remove `trigger: false` as this is the default
> Introduce run-unit-specs task

- src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb
New series AMD for 7th generation plus adding the r7i.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#instance-hypervisor-type
```
General purpose: M5 | M5a | M5ad | M5d | M5dn | M5n | M5zn | M6a | M6g | M6gd | M6i | M6id | M6idn | M6in | **M7a** | M7g | M7gd | M7i | M7i-flex | M8g | T3 | T3a | T4g
Compute optimized: C5 | C5a | C5ad | C5d | C5n | C6a | C6g | C6gd | C6gn | C6i | C6id | C6in | **C7a** | C7g | C7gd | C7gn | C7i | C7i-flex | C8g
Memory optimized: R5 | R5a | R5ad | R5b | R5d | R5dn | R5n | R6a | R6g | R6gd | R6i | R6idn | R6in | R6id | **R7a** | R7g | R7gd | **R7i** | R7iz | R8g | U-3tb1 | U-6tb1 | U-9tb1 | U-12tb1 | U-18tb1 | U-24tb1 | U7i-12tb | U7in-16tb | U7in-24tb | U7in-32tb | X2gd | X2idn | X2iedn | X2iezn | X8g | z1d
```
> adding 7th gen machines with amd and intel

- jobs/aws_cpi/spec
- src/bosh_aws_cpi/lib/cloud/aws/config.rb
- src/bosh_aws_cpi/spec/unit/config_spec.rb
Currently, `role_arn` is only used when `credentials_source: static` is configured, allowing the use of an assumed role. This change extends the functionality to also support `credentials_source: env_or_profile` in combination with `role_arn`.
This would, for instance, allow the creation of a bosh director, even if the director VM will not reside in the same AWS account to which the creating VM's instance profile belongs.
> Allow use of assumed roles through role_arn when using credentials_source: env_or_profile

- jobs/aws_cpi/templates/cpi.json.erb
- src/bosh_aws_cpi/lib/cloud/aws/cloud_v3.rb
- src/bosh_aws_cpi/lib/cloud/aws/config.rb
- src/bosh_aws_cpi/spec/unit/bosh_release/jobs/cpi/templates/cpi.json.erb_spec.rb
- src/bosh_aws_cpi/spec/unit/cloud_v3_spec.rb
Fixes the logic for tagging ami images on stemcell creation and bumps up the debug.cpi.api_version default value and MAX_SUPPORTED_API_VERSION to 3.
Follow up PR for [Apply tags on stemcell creation](https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/177)
> Update debug API version to 3 and fix AMI tagging logic
